flow_module: flows.deploy_flow
        
deploy:
    model_metadata_file_name: animals10_classifier_50px_trial7.yaml
    prefect:
        work_root: ~/workspace/deploy/evidently_workspaces
        # this should match the deployment name in prefect.yaml 
        # at the root of the specified repo
        deployment_name: drift_detection_evidently